### ISSUE TITLE
"Syntax in a postcard = Simple" could be argued

### ISSUE THREAD

**Issue by hernanmd** [SquareBracketAssociates/PharoByExample9#18]
"A dynamically-typed language with a syntax so simple it can fit on a postcard"

It could be argued that fitting in a post-card does not seem to be a strong metric for a programming language simplicity. Some posts for example on Quora [commenting about this sentence](https://www.quora.com/Is-there-a-programming-language-small-enough-to-fit-on-a-postcard) and [another one with a sound counter-example was posted](https://www.quora.com/Which-programming-language-has-the-easiest-syntax). The OP mentions that the something similar could be said for a (toy?) programming language called Brainfuck. Probably its syntax fits in a postcard but being extremely difficult to use.

Probably a rephrase could avoid unnecessary controversy. Something like:  "A dynamically-typed language with a minimalist syntax, similar to natural language writing, and it can fit on a postcard"

**Comment by Ducasse** [comment]
ok with me.
