### ISSUE TITLE
Update Iceberg section for Github token based authentication

### ISSUE THREAD

**Issue by hernanmd** [SquareBracketAssociates/PharoByExample9#19]
Since January 11, 2022 Github [removed support](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) for password based authentication using HTTPS. Also the usage of RSA key with SHA-1 is no longer allowed.

Additionally, this startup action is useful for addressing GitHub changes and could be a time-saver for many people reading PBE 9:

```smalltalk
StartupPreferencesLoader default executeAtomicItems: {
    StartupAction 
        name: 'Logo' 
        code: [ PolymorphSystemSettings showDesktopLogo: false] .
    StartupAction 
        name: 'Git Settings' 
        code: [ 
            Iceberg enableMetacelloIntegration: true.
            IceCredentialStore current
                    storeCredential: (IcePlaintextCredentials new
                    username: 'xxxxx';
                    password: 'xxxx';
                    host: 'github.com';
                    yourself).        
            IceCredentialStore current
                storeCredential: (IceTokenCredentials new
                    username: 'your-github-username';
                    token: 'magictoken here ';
                    yourself) 
                forHostname: 'github.com'.
            ]. 
}.
```

**Comment by Ducasse** [comment]
Yes!!!

**Comment by Ducasse** [comment]
Here is what I added to the iceberg booklet

!!! Configuring automatically Pharo to commit in HTTPS

With recent version of github, you should use a token to connect using HTTPS to be able to commit to your repository.
Now you can configure Pharo to store your token as well your github account authentification. 

[[[
StartupPreferencesLoader default executeAtomicItems: {
    StartupAction 
        name: 'Logo' 
        code: [ PolymorphSystemSettings showDesktopLogo: false] .
    StartupAction 
        name: 'Git Settings' 
        code: [ 
            Iceberg enableMetacelloIntegration: true.
            IceCredentialStore current
                    storeCredential: (IcePlaintextCredentials new
                    username: 'xxxxx';
                    password: 'xxxx';
                    host: 'github.com';
                    yourself).        
            IceCredentialStore current
                storeCredential: (IceTokenCredentials new
                    username: 'your-github-username';
                    token: 'magictoken here ';
                    yourself) 
                forHostname: 'github.com'.
            ]. 
}
]]]

**Comment by Ducasse** [comment]
I added in the chapter IcebergIntro/Configuration

**Comment by Ducasse** [comment]
I do not know. We should check.
