### ISSUE TITLE
http://files.pharo.org/get/ doesn't work (404) - should be files.pharo.org/get-files or get.pharo.org?

### ISSUE THREAD

**Issue by bcasiello** [SquareBracketAssociates/PharoByExample9#2]
https://github.com/SquareBracketAssociates/PharoByExample9/blob/546c70becbc6939a252f8c87a3d1d0e20eecb84e/Chapters/PharoTour/PharoTour.pillar#L45

The link http://files.pharo.org/get/ fails for me with a 404.
http://files.pharo.org/get-files/ does resolve, but unclear how to get to the zeroconf files mentioned.

get.pharo.org as shown in the snippet seems to be the relevant url.

**Comment by gypsydave5** [comment]
Yup, I think that should be `https://get.pharo.org/` too; it'll go in the update for the chapter.
