### ISSUE TITLE
Script or Listing 10-34 misplace in context

### ISSUE THREAD

**Issue by sleepnova** [SquareBracketAssociates/PharoByExample9#22]
At latest build 8dfd9b7
Chapter 10.23 P.143

The last line says "its definition is shown below in Script 10-34" but it's actually above.
<img width="746" alt="截圖 2022-02-06 下午11 55 00" src="https://user-images.githubusercontent.com/86796/152689434-c3dd5cdd-83b3-4451-80e1-6a0e73af3c99.png">

**Comment by hernanmd** [comment]
As this could mean some changes in the Pillar core to generate the right raw LaTeX listing, I propose for now to remove the "below" since any reader could scroll a bit above to find the figure.

**Comment by Ducasse** [comment]
indeed we do not control latex placement. So we should just remove below.
