### ISSUE TITLE
No TDD in chapter 5, contrary to what chapter 4 says

### ISSUE THREAD

**Issue by jmiven** [SquareBracketAssociates/PharoByExample9#25]
The end of chapter 4 talks about using TDD next:

> Now let’s take a look at some other other tools in Pharo, while we write a new method through the technique of Test-Driven Development.

But the Counter of chapter 5 is developed *without* TDD.

**Comment by Ducasse** [comment]
Thanks!!!

**Comment by hernanmd** [comment]
There is already a TDD chapter in a file called "Extracted.pillar" but it's not present in index.pillar. However it is not applied to a Counter but a separate example. This chapter could be re-introduced or the text at the end of Chapter 4 could be updated to remove the TDD mention.

**Comment by Ducasse** [comment]
Hernan I would like to finish and get the book publish so the best is to just remove the TDD mention. The fact that the book get slimmer is better.
