### ISSUE TITLE
Actual title is "Inspector on 7"

### ISSUE THREAD

**Issue by bcasiello** [SquareBracketAssociates/PharoByExample9#3]
https://github.com/SquareBracketAssociates/PharoByExample9/blob/546c70becbc6939a252f8c87a3d1d0e20eecb84e/Chapters/PharoTour/PharoTour.pillar#L403

The text says the title of the Inspector window is "Inspector on a SmallInteger(7)", but as shown in the illustration, it's actually "Inspector on 7" and slightly below that is "a SmallInteger(7)".

**Comment by gypsydave5** [comment]
https://github.com/SquareBracketAssociates/PharoByExample9/pull/11
