### ISSUE TITLE
Menu name not updated from Tools to Browse

### ISSUE THREAD

**Issue by CodingItWrong** [SquareBracketAssociates/PharoByExample9#4]
The "first application" chapter references "Tools > Iceberg", but this seems like it should be "Browse > Iceberg" in Pharo 9

https://github.com/SquareBracketAssociates/PharoByExample9/blob/69ef921a102104e007388f72d17a5ce1e30dc891/Chapters/FirstApplication/FirstApplication.pillar#L662

**Comment by gypsydave5** [comment]
Yup, agreed. Also not sure how appropriate another Iceberg tutorial is here, given that we just did one in the Counter example.

I'm taking a look at this chapter next

**Comment by Ducasse** [comment]
Tx we will update the book.

**Comment by hernanmd** [comment]
I saw the section "Declared repositories" was removed already.
Now there is "Open Iceberg through the ""Sources"" menu, or by hitting ==Cmd-O,I==." in the Exo-Counter.pillar.
So this could be closed.

**Comment by Ducasse** [comment]
We should pay attention because the more precise we are the more changes we prepare to change in the future versions. I think that people should be able to find a menu entry.

**Comment by Ducasse** [comment]
I improved the description and now we can close this issue.
