### ISSUE TITLE
Has not "Basic Inspect it"

### ISSUE THREAD

**Issue by mr-Serg** [SquareBracketAssociates/PharoByExample9#43]
Chapter 3.7 Other operations talks about the command "Basic Inspect it", but in Pharo 90 Playground does not contain it among right-click options. It would be nice to remove the paragraph.

**Comment by Ducasse** [comment]
Thanks for the feedback.

**Comment by mr-Serg** [comment]
I am working on translation and check all things

**Comment by Ducasse** [comment]
I know the feeling because I translated some books too and I spotted many inconsistency.

**Comment by Ducasse** [comment]
I took that into account
