### ISSUE TITLE
10.26 Incorrect description of relative position of Listing 10-41 and text

### ISSUE THREAD

**Issue by sleepnova** [SquareBracketAssociates/PharoByExample9#45]
"(see the method definition below)%Script 10-41)" is actually above.

<img width="961" alt="截圖 2022-04-24 下午4 07 47" src="https://user-images.githubusercontent.com/86796/164966702-8a39ed07-b62e-4fb4-ad07-a50880171a18.png">

**Comment by Ducasse** [comment]
The text is correct the redefinition is below.
