### ISSUE TITLE
Several mistakes in the Chapter 5

### ISSUE THREAD

**Issue by mr-Serg** [SquareBracketAssociates/PharoByExample9#48]
p. 35 "much as we saw in the last chapter" - wrong statment, it was in the previous version of the book, there NOTHING about TDD in Chapter 4 now.
p. 37 "There are FIVE parts you might want to change" - but there are only FOUR parts described.
      it would be better to mention about Package Specification. Or not?
p. 43 "or using the Test Runner available in the Tools menu." - there is not item Tools in World menu now. There is Browse instead.
p. 44 "Once you package is added, Iceberg shows you that there is uncommitted code in the packages managed by your project, as shown in Figure 5-11." but it is talking about Figure 5-10
p. 48 "However, as we mentioned, the initialize message is sent to the newly created instance." - we do not mention abot initialize message yet. It would be nice to explain the initialization process.
      Comment: "set the initial value of the VALUE to 0" sould be "set the initial value of the count to 0"
p. 50-51 the project MyCounter is mentioned as Counter
p. 51 "HTTPS will require you to enter your user name and password" but GitHub does not allow access throu password now, we should use the personal access token instead
p. 52 "Figure 5-16 GitHub HTTPS address OUR our project." sould be "of our project"

**Comment by Ducasse** [comment]
Thanks for recording these mistakes.

**Comment by Ducasse** [comment]
I will update the book for the pharo 10 version or so because now it has been sent to the printer in any case this is good to 
be able to fix this in the future

**Comment by mr-Serg** [comment]
To be continued...

нд, 22 трав. 2022, 15:35 користувач StéphaneDucasse <
***@***.***> пише:

**Comment by mr-Serg** [comment]
This is a difficult task to be "up to date" with the new version of Pharo :)

нд, 22 трав. 2022, 15:36 користувач StéphaneDucasse <
***@***.***> пише:

**Comment by Ducasse** [comment]
p. 44 "Once you package is added, Iceberg shows you that there is uncommitted code in the packages managed by your project, as shown in Figure 5-11." but it is talking about Figure 5-10
I checked and it is correct.

**Comment by Ducasse** [comment]
about initialize I wrote

```
Now we have to write an initialization method that sets a default value of the ==count== instance variable.
In Pharo, when creating a new object sending the message ==new== to a class, the newly created instance is sent a message ==initialize==. This gives the opportunity to the instance to initialize itself. 
Therefore we will define a ==initialize== method that will correctly initialize the default value of a counter. 

Since the ==initialize== messsage is sent to a new instance, it means that the ==initialize== method should be defined on the ''instance side'', just like any method that is sent to an instance of ==Counter== (==increment== and ==decrement==). The ==initialize== method is responsible for setting up the default values of instance variables.

And so, on the instance side of ==Counter==, and in the ==initialization== protocol, write the following method (the body of this method is left blank. Fill it in!).

[[[
Counter >> initialize
  "set the initial value of count to 0"

  "Your code here""
]]]

If you do this right, our ==testInitialize== test will now pass.

As always, save your work before moving on to the next step.
```

**Comment by Ducasse** [comment]
I addressed all the points.
