### ISSUE TITLE
Several mistakes in the Chapter 6

### ISSUE THREAD

**Issue by mr-Serg** [SquareBracketAssociates/PharoByExample9#49]
There are not any reference to the Figure 6-2. Is this figure really neccessary? Figure 6-2 is very similar to figure 6-3.

p. 59 The link https://c2.com/doc/oopsla89/paper.html does not work. May be it would be better to use https://dl.acm.org/doi/pdf/10.1145/74878.74879
p. 61 "To refresh the values, click on the update button (the blue little circle)..." - There are not "update" button in the Inspector's window. It is Refresh button, but we do not need to click it because the value updates automaticly. By the way, the using of rotate handle of the cell's morphic halo frustrates the Inspector
p. 63 Figure 6-10: The value of bounds cotradicts with the text above. It should be "(200@200) corner: (250@250)", or at least it must coressponds to the second pane of Inspector
p. 64 "Type the contents of 6-17" should be "Type the contents of Listing 6-12"
p. 65 "and opens... the Debugger again on the method definition." should be "and opens... the Debugger again on the method definition (see Figure 6-15)."
p. 66 "we haven’t defined the method newCellAt:." shold be "we haven’t defined the method newCellAt:at:."
p. 67 Listing 6-17 is the exect copy of Listing 6-12. It would be better to keep the approach of the previous version of the book and have numbered lines in the listsing 6-17

p. 71 Listing 6-21 and the explanation in the text make me frustrated! Listing: "self toggleState". Text: "First, this method toggles the state of the current cell." - WHY!!! See 6.1 The Lights Out game: "When you click on one of the cells, the four surrounding cells turn blue." ONLY four surrounding cells, not the cell have been clicked. "self toggleState" and corresponding explanation should be removed.

p. 76 Subsection 6.17 is very far from the place where mouseAction variable were declared, so it is unexpected and is not clear to talk about accessors (accessors to what?) after the "file in fileout".

**Comment by Ducasse** [comment]
The link is working for me

**Comment by Ducasse** [comment]
Thanks I will take these comments for Pharo 12 by example probably. 
It is a pity that I sent too early.

**Comment by mr-Serg** [comment]
Ok. May be this is only my problem, but ... if anyone else will face this
problem with SSL protocol?
[image: image.png]

чт, 9 черв. 2022 р. о 01:12 StéphaneDucasse ***@***.***> пише:

**Comment by Ducasse** [comment]
Indeed and I do not even know why we need this reference

**Comment by Ducasse** [comment]
There are not any reference to the Figure 6-2. Is this figure really neccessary? Figure 6-2 is very similar to figure 6-3.

=> I removed it.

**Comment by Ducasse** [comment]
p. 59 The link https://c2.com/doc/oopsla89/paper.html does not work. May be it would be better to use https://dl.acm.org/doi/pdf/10.1145/74878.74879
=> removed!

**Comment by Ducasse** [comment]
p. 61 "To refresh the values, click on the update button (the blue little circle)..." - There are not "update" button in the Inspector's window. It is Refresh button, but we do not need to click it because the value updates automaticly. By the way, the using of rotate handle of the cell's morphic halo frustrates the Inspector

=> I modified a bit the text and removed update and used refreshed instead.

**Comment by Ducasse** [comment]
p. 63 Figure 6-10: The value of bounds cotradicts with the text above. It should be "(200@200) corner: (250@250)", or at least it must coressponds to the second pane of Inspector

=> this bounds: stuff is a bad idea. I removed figure 6-10.

This chapter is too clumsy. Too many details for nothing. I never like it. 
Now this is good that I added the counter tutorial because the first contact with Pharo was lengthly and boriiiiiing.

**Comment by Ducasse** [comment]
p. 64 "Type the contents of 6-17" should be "Type the contents of Listing 6-12"
p. 65 "and opens... the Debugger again on the method definition." should be "and opens... the Debugger again on the method definition (see Figure 6-15)."
=> fixed

**Comment by Ducasse** [comment]
p. 66 "we haven’t defined the method newCellAt:." shold be "we haven’t defined the method newCellAt:at:."
=> done

**Comment by Ducasse** [comment]
p. 76 Subsection 6.17 is very far from the place where mouseAction variable were declared, so it is unexpected and is not clear to talk about accessors (accessors to what?) after the "file in fileout".
=> reorganized the section + simplify the save subsection

**Comment by Ducasse** [comment]
left so far

- p. 67 Listing 6-17 is the exect copy of Listing 6-12. It would be better to keep the approach of the previous version of the book and have numbered lines in the listsing 6-17
- p. 71 Listing 6-21 and the explanation in the text make me frustrated! Listing: "self toggleState". Text: "First, this method toggles the state of the current cell." - WHY!!! See 6.1 The Lights Out game: "When you click on one of the cells, the four surrounding cells turn blue." ONLY four surrounding cells, not the cell have been clicked. "self toggleState" and corresponding explanation should be removed.

**Comment by Ducasse** [comment]
p. 67 Listing 6-17 is the exect copy of Listing 6-12. It would be better to keep the approach of the previous version of the book and have numbered lines in the listsing 6-17

=> the template changed and I do not know how to control it. So it will be for later.

**Comment by Ducasse** [comment]
p. 71 Listing 6-21 and the explanation in the text make me frustrated! Listing: "self toggleState". Text: "First, this method toggles the state of the current cell." - WHY!!! See 6.1 The Lights Out game: "When you click on one of the cells, the four surrounding cells turn blue." ONLY four surrounding cells, not the cell have been clicked. "self toggleState" and corresponding explanation should be removed.

I do not think that removing toggleState is correct. If we do this the cell that is clicked will not be changed and we should changed it too.

**Comment by Ducasse** [comment]
From wikipedia: 'Pressing any of the lights will toggle it and the adjacent lights.'
so I will change the beginning to be 
When you click on one of the cells, the four surrounding cells turn blue. ->
When you click on one of the cells, the cell and its the four surrounding cells turn blue.

**Comment by LNUitTutor** [comment]
It's a pity, because I just found the nice solving algorithm :)

**Comment by Ducasse** [comment]
:)
But you can do a variation or several variations
