### ISSUE TITLE
Seaside chapter is missing

### ISSUE THREAD

**Issue by cwfoo** [SquareBracketAssociates/PharoByExample9#54]
The [chapter about Seaside](https://github.com/SquareBracketAssociates/PharoByExample9/tree/16100b6c4a8d28024429a4eb809a7cb02bd4d7f4/Chapters/Seaside) is missing from the generated PDF.

**Comment by Ducasse** [comment]
I will check but I think that this is on purpose. You have a full book on seaside available at http://book.seaside.st
