### ISSUE TITLE
Some questions to the Chapter 8

### ISSUE THREAD

**Issue by mr-Serg** [SquareBracketAssociates/PharoByExample9#55]
p. 97 "more detailed description is provided in Chapter : Understanding messages." There are not such chapter in the book. It should be "Understanding message syntax"

p. 101 "Some conditionals"  Is the message ifFalse:ifTrue: missed?
       "Some loops" How about message to:by:do:? and sending it to reals? 
       "Since the exit condition for a loop may be repeatedly evaluated, it should be a block rather than a boolean value." - inaccuracy: "a boolean value" - true or false - is constant. True in a loop condition gives us a permanent loop. I never need a permanrnt loop. It should be better to say "a logical expression".
       "whileFalse: reverses the exit condition" a little error in the example: reverse to the (n<100) is (n>=1000). Not (n > 1000)
An interesting question: is the (n<1000) in [n<1000] whileTrue:[] "exit condition" or "continuation condition"?

p. 104 "There are three kinds of messages: unary (e.g., 1 asString, Array new)" - is the "Array new" a qood example? We use as usual "Array new: size". May be "Time now" or "Date today" instead?
       "binary (e.g., 3 + 4, 'hi', ' there')" - a problem with comma: it is a separator between examples, and it is a message in the second example. May be to use semicolon to separate examples?
       "'hi' at: 2 put: $o" - ERROR!!! The strings became immutable in Pharo 9.0. May be inject:into: or to:by:
       "until you send the block a value message" - need we to select the word "value" by formatting?

**Comment by Ducasse** [comment]
p. 97 "more detailed description is provided in Chapter : Understanding messages." There are not such chapter in the book. It should be "Understanding message syntax"
=> done but it was the same at the end.

**Comment by Ducasse** [comment]
"'hi' at: 2 put: $o" - ERROR!!! The strings became immutable in Pharo 9.0. May be inject:into: or to:by:
=> indeed I will fix this.

**Comment by Ducasse** [comment]
p. 104 "There are three kinds of messages: unary (e.g., 1 asString, Array new)" - is the "Array new" a qood example? We use as usual "Array new: size". May be "Time now" or "Date today" instead?

**Comment by Ducasse** [comment]
Since the exit condition for a loop may be repeatedly evaluated, it should be a block rather than a boolean value." - inaccuracy: "a boolean value" - true or false - is constant.
=> what is written is correct. I changed to boolean expression

**Comment by Ducasse** [comment]
p. 104 "There are three kinds of messages: unary (e.g., 1 asString, Array new)" - is the "Array new" a qood example? We use as usual "Array new: size". May be "Time now" or "Date today" instead?

=> I want a new message! So I put OrderedCollection new (but Array new is valid - this is an empty array.

**Comment by Ducasse** [comment]
"binary (e.g., 3 + 4, 'hi', ' there')" - a problem with comma: it is a separator between examples, and it is a message in the second example. May be to use semicolon to separate examples?
=> I use or


"'hi' at: 2 put: $o" - ERROR!!! The strings became immutable in Pharo 9.0. May be inject:into: or to:by:

=> I use 5 between: 2 and: 10

**Comment by Ducasse** [comment]
"until you send the block a value message" - need we to select the word "value" by formatting?

=>
The expressions in a block are not evaluated until you send the block a value (==value==, ==value:==, ==value:value:==, ...) message with the correct number of arguments. ==[ :x | x + 2 ] value: 4==
