### ISSUE TITLE
Short comment to Chapter 11

### ISSUE THREAD

**Issue by mr-Serg** [SquareBracketAssociates/PharoByExample9#58]
p. 151 A unigue caption "Listing 11-1 A simple trait." would be deleted. It is unique for all the chapter, so...

p. 152 typo: "the trait TGreetable in invoking the method" should be "is invoking"

p. 153 typo:
- "s an instance variable named #count." OR count ???
- "... by defining a method initialize followed by the class named." should be "trait name"

p. 156 typo: "overriddent" - ???

Several important things were left "behind the scene":
- can we create an instance of a trait - No
- how can I define a new trait? In the previous book were few words about Brouser and corresponding command such "New trait"
- can I inherit the class that uses a trait - what will happen? What will happen if Bird uses TFlyingAbility, Eagle uses THighFlyingAbility, and Eagle inherits Bird? What metod fly will act? Will the conflict raise? - No, because ... - this may be interesting.

**Comment by Ducasse** [comment]
I fixed everything. 
I added a section on traits and inheritance.
