### ISSUE TITLE
Short comment to Chapter 15

### ISSUE THREAD

**Issue by mr-Serg** [SquareBracketAssociates/PharoByExample9#62]
There are many fragments of the text like "the method defined in the Class". It would be really simple to write "Class>>method" instead.

p. 221
- 'This image contains: 9003 classes. - H-m-m, the fresh image of Pharo 9.0 contains about 10672 classes
- "The message streamContents: defined SequenceableCollection creates" - are some words missing? May be "The message streamContents: defined in SequenceableCollection class creates"?

p. 222
- "the best way to concatenate characters." But we do not concatenate Characters - we concatenate Strings!
- "Basically the Object>>#printString method ..." should be Object>>printString

p. 224 "printProtocol: protocol sourceCode: sourceCode" name of the class missing. Is it EpContentStringVisitor?

pp. 225,226 On my mind, it would be better to show element nil after page# on the streams at Figures 15.5-15.11

**Comment by Ducasse** [comment]
There are many fragments of the text like "the method defined in the Class". It would be really simple to write "Class>>method" instead.

I do not like both because we do not really care about the method. The message is more important. 
I added a little section explaining that the reader should focus on messages. And I will check if I can remove some of the defined in.

**Comment by Ducasse** [comment]
'This image contains: 9003 classes. - H-m-m, the fresh image of Pharo 9.0 contains about 10672 classes

I put XXXX because I do not want to change this for every single image.

**Comment by Ducasse** [comment]
"the best way to concatenate characters." But we do not concatenate Characters - we concatenate Strings!

I changed to " add characters to a string" but concatenate characters was correct.

**Comment by Ducasse** [comment]
"Basically the Object>>#printString method ..." should be Object>>printString

Fixed

p. 224 "printProtocol: protocol sourceCode: sourceCode" name of the class missing. Is it EpContentStringVisitor?

Fixed. I added that people do not have to care of the exact class.

**Comment by Ducasse** [comment]
pp. 225,226 On my mind, it would be better to show element nil after page# on the streams at Figures 15.5-15.11

I do not want to put nil because we could have initialize the container with null like objects and not necessarily nil. 
So let us keep it like that.
